---
# Usage: http://ruhoh.com/usage/configure/ 

RuhohSpec: '1.0'
theme : twitter
production_url : http://defworld.com

posts:
  permalink: /:year-:month/:filename.html
  summary_lines: 10
  latest: 10
  layout: 'post' # default
  exclude: '~$'

pages:
  permalink: 'pretty' # page file path simple mapping
  layout: 'page' # default
  exclude: '~$'
