title : tiemei
tagline: Blog Tagline
author :
  name : tiemei
  email : jiadongkai@gmail.com
  github : tiemei
  twitter : tiemei
  feedburner : tiemei

navigation :
  - archive.html
  - blogs/index.md
  - categories.html
  - tools/index.md
  
